import "./globals.css";
import TopBarWrapper from "../components/TopBarWrapper"; // client wrapper
import SidebarWrapper from "../components/SidebarWrapper"; // client wrapper
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* Client-side TopBar logic */}
        <TopBarWrapper />

        <div className="flex h-[calc(100vh-3.5rem)] overflow-hidden">
          {/* Client-side Sidebar logic */}
          <SidebarWrapper />

          <div className="flex-1 overflow-y-auto bg-[#EDF0F5]">{children}</div>
        </div>
      </body>
    </html>
  );
}